import i18n from 'i18next'
import frSupplement from './translations-fr'
import accountFr from './translations-account-fr'
import dashboardFr from './translations-dashboard-fr'
import publicFr from './translations-public-fr'
import miscFr from './translations-misc-fr'

// English source strings are stable translation keys; event/organizer-supplied copy is never
// translated unless it exactly matches a platform string in this catalog.
const fr: Record<string, string> = {
  'Choose language': 'Choisir la langue',
  'Language': 'Langue', 'English': 'Anglais', 'Français': 'Français',
  'Discover events': 'Découvrir les événements', 'Discover': 'Découvrir', 'About': 'À propos', 'For Organizers': 'Pour les organisateurs',
  'Discover events near you': 'Découvrez les événements près de chez vous', 'Discover what is happening near you': 'Découvrez ce qui se passe près de chez vous',
  'Find events nearby': 'Trouvez des événements près de chez vous', 'Find your next event': 'Trouvez votre prochain événement',
  'Search events, artists, venues…': 'Rechercher des événements, artistes, lieux…', 'Search events': 'Rechercher des événements', 'Search organizers': 'Rechercher des organisateurs',
  'Clear search': 'Effacer la recherche', 'Filters': 'Filtres', 'All events': 'Tous les événements', 'All types': 'Tous les types', 'All prices': 'Tous les prix', 'Any price': 'Tous les prix',
  'Today': 'Aujourd’hui', 'Tomorrow': 'Demain', 'This weekend': 'Ce week-end', 'Tonight': 'Ce soir', 'Music': 'Musique', 'Free': 'Gratuit', 'Paid': 'Payant',
  'EVENT TYPE': 'TYPE D’ÉVÉNEMENT', 'PRICE': 'PRIX', 'PRICE RANGE': 'FOURCHETTE DE PRIX', 'SORT BY': 'TRIER PAR',
  'Newest first': 'Les plus récents', 'By date': 'Par date', 'Price: Low to high': 'Prix croissant', 'Price: High to low': 'Prix décroissant',
  'Live': 'En direct', 'Live now:': 'En direct :', 'No events are live right now. Check back soon.': 'Aucun événement en direct pour le moment. Revenez bientôt.',
  'Trending events': 'Événements populaires', 'Popular picks, ranked by live ticket sales': 'Les événements populaires, classés selon les ventes de billets', 'Active events': 'Événements à venir', 'Events happening near you': 'Les événements près de chez vous',
  'Free to attend': 'Gratuit', 'Good times, no ticket required': 'De bons moments, sans billet requis', 'Search results': 'Résultats de recherche', 'Loading...': 'Chargement…', 'Loading…': 'Chargement…',
  'event to explore': 'événement à découvrir', 'events to explore': 'événements à découvrir', 'Clear all': 'Tout effacer', 'No events available': 'Aucun événement disponible',
  'No events found': 'Aucun événement trouvé', 'No published events yet. Check back soon or create your own.': 'Aucun événement publié pour le moment. Revenez bientôt ou créez le vôtre.', 'Try different filters or search terms.': 'Essayez d’autres filtres ou termes de recherche.', 'Clear filters': 'Effacer les filtres', 'View all events': 'Voir tous les événements', 'Explore all events': 'Explorer tous les événements',
  'Meet the organizers': 'Rencontrez les organisateurs', 'Discover the people behind the events': 'Découvrez les personnes derrière les événements', 'View all organizers': 'Voir tous les organisateurs',
  'Have an event?': 'Vous organisez un événement ?', 'Create, sell and manage your tickets in one place. Reach thousands of people across Burundi and beyond.': 'Créez, vendez et gérez vos billets au même endroit. Touchez des milliers de personnes au Burundi et ailleurs.', 'Start for free': 'Commencer gratuitement', 'Learn more': 'En savoir plus',
  'Events': 'Événements', 'Tickets': 'Billets', 'My Tickets': 'Mes billets', 'Get Tickets': 'Obtenir des billets', '+ Get Tickets': '+ Obtenir des billets', 'View ticket': 'Voir le billet', 'View my ticket': 'Voir mon billet', 'View my tickets': 'Voir mes billets', 'Browse Events': 'Parcourir les événements', 'Browse events': 'Parcourir les événements',
  'Sign in': 'Se connecter', 'Sign In': 'Se connecter', 'Sign out': 'Se déconnecter', 'Create Event': 'Créer un événement', 'Create an event': 'Créer un événement', 'Create account': 'Créer un compte', 'Profile': 'Profil', 'Favorites': 'Favoris', 'Notifications': 'Notifications', 'Alerts': 'Alertes', 'Dashboard': 'Tableau de bord', 'Agent Dashboard': 'Tableau de bord de l’agent', 'Accept invite': 'Accepter l’invitation', 'Accept organizer invite': 'Accepter l’invitation de l’organisateur',
  'Open navigation menu': 'Ouvrir le menu de navigation', 'Close navigation menu': 'Fermer le menu de navigation', 'Menu': 'Menu',
  'For Organizers': 'Pour les organisateurs', 'Host an event': 'Organiser un événement', 'Start hosting': 'Commencer à organiser', 'Become an organizer': 'Devenir organisateur', 'Your event deserves': 'Votre événement mérite',
  'What is Tiketi?': 'Qu’est-ce que Tiketi ?', 'Tiketi is a platform for discovering events, buying tickets, and helping organizers bring their experiences to audiences across Burundi.': 'Tiketi est une plateforme qui permet de découvrir des événements, d’acheter des billets et d’aider les organisateurs à faire connaître leurs expériences au public burundais.',
  'Who can create an event?': 'Qui peut créer un événement ?', 'Organizers, event teams, venues, and approved event partners can use Tiketi to bring their events online.': 'Les organisateurs, équipes événementielles, salles et partenaires agréés peuvent utiliser Tiketi pour publier leurs événements en ligne.',
  'How do I get my ticket?': 'Comment recevoir mon billet ?', 'After completing your booking, your ticket and confirmation are kept in your Tiketi account for easy access.': 'Une fois votre réservation terminée, votre billet et sa confirmation sont conservés dans votre compte Tiketi pour y accéder facilement.',
  'Where is Tiketi available?': 'Où Tiketi est-il disponible ?', 'Tiketi is built for Burundi, starting with the country’s active event communities and expanding as the platform grows.': 'Tiketi est conçu pour le Burundi, en commençant par les communautés événementielles du pays et en s’étendant avec la plateforme.',
  'Can I get help with an event?': 'Puis-je obtenir de l’aide pour un événement ?', 'Yes. Tiketi provides support for ticketing and platform-related questions. For event-specific issues, we can also connect you with the organizer when needed.': 'Oui. Tiketi vous aide pour les billets et les questions liées à la plateforme. Pour les questions propres à un événement, nous pouvons aussi vous mettre en relation avec son organisateur.',
  'The home for Burundi’s live culture': 'Le foyer de la culture vivante du Burundi', 'Moments worth': 'Des moments qui méritent', 'showing up for.': 'qu’on se déplace.',
  'Tiketi helps people discover what is happening across Burundi and gives organizers a simple, trusted way to sell tickets, manage events, and bring people together.': 'Tiketi aide le public à découvrir les événements au Burundi et offre aux organisateurs un moyen simple et fiable de vendre des billets, gérer leurs événements et rassembler les gens.',
  'Featured events': 'À la une', 'What is happening': 'Ce qui se passe', 'right now.': 'en ce moment.', 'New experiences are coming soon.': 'De nouvelles expériences arrivent bientôt.', 'Browse all events': 'Voir tous les événements',
  'Why Tiketi': 'Pourquoi Tiketi', 'Less searching.': 'Moins de recherches.', 'More showing up.': 'Plus de moments partagés.', 'There is always something happening in Burundi. Tiketi makes the good stuff easier to discover, trust, book, and be part of.': 'Il se passe toujours quelque chose au Burundi. Tiketi facilite la découverte, la réservation et la participation aux meilleurs événements.',
  'TONIGHT': 'CE SOIR', 'Find your': 'Trouvez votre', 'next thing.': 'prochaine sortie.', 'is alive': 'est en fête', 'See what is happening': 'Voir ce qui se passe',
  'Our impact': 'Notre impact', 'More people in': 'Plus de monde', 'the room.': 'dans la salle.', 'Every organizer who launches and every attendee who shows up helps build a more connected event community in Burundi.': 'Chaque organisateur qui se lance et chaque participant présent contribue à créer une communauté événementielle plus connectée au Burundi.',
  'Discoverable events': 'Événements à découvrir', 'For the ticket journey': 'Pour tout le parcours du billet', 'Built around people': 'Conçu pour les gens', 'Reasons to show up': 'Raisons de se retrouver', 'Book': 'Réserver', 'Experience': 'Vivre', 'Repeat': 'Recommencer',
  'From discovery to the door': 'De la découverte à l’entrée', 'Everything you need,': 'Tout ce qu’il vous faut,', 'in your pocket.': 'dans votre poche.', 'Tiketi keeps the event journey simple. Explore what is on, follow what matters, book when you are ready, and arrive with confidence.': 'Tiketi simplifie votre parcours événementiel. Explorez les événements, suivez ceux qui vous intéressent, réservez quand vous le souhaitez et présentez-vous en toute confiance.',
  'DISCOVER': 'DÉCOUVRIR', 'FOLLOW': 'SUIVRE', 'BOOK': 'RÉSERVER', 'WALK IN': 'ENTRER', 'Find what is happening near you': 'Découvrez ce qui se passe près de chez vous', 'Browse concerts, parties, culture, sports, community events, and the experiences worth leaving home for.': 'Parcourez les concerts, soirées, événements culturels, sportifs et communautaires qui valent le détour.',
  'Never miss the ones you care about': 'Ne manquez plus ce qui compte pour vous', 'Follow organizers and experiences that feel like you. Tiketi keeps the events you care about closer.': 'Suivez les organisateurs et les expériences qui vous ressemblent. Tiketi vous rapproche des événements qui comptent.',
  'Book in seconds': 'Réservez en quelques secondes', 'Choose your ticket, review the details, complete your booking, and keep your confirmation where you need it.': 'Choisissez votre billet, vérifiez les détails, finalisez votre réservation et gardez votre confirmation à portée de main.', 'Browse tickets': 'Parcourir les billets', 'Straight through the door': 'Entrez sans attendre', 'Keep your ticket ready on your phone and arrive prepared for the experience.': 'Gardez votre billet sur votre téléphone et préparez-vous à profiter de l’événement.',
  'What we believe': 'Nos convictions', 'Technology with': 'La technologie au service', 'a human pulse.': 'de l’humain.', 'Make it feel local': 'Ancrer l’expérience localement', 'Keep it simple': 'Faire simple', 'Grow the ecosystem': 'Faire grandir l’écosystème',
  'The best events feel connected to the people around them. Tiketi helps local experiences get discovered by the audiences they are meant for.': 'Les meilleurs événements sont proches de leur communauté. Tiketi aide le public concerné à découvrir les expériences locales.',
  'From the first tap to the ticket at the door, every part of the journey should feel clear, quick, and human.': 'Du premier clic au billet présenté à l’entrée, chaque étape doit être claire, rapide et humaine.',
  'Organizers, artists, venues, agents, brands, and audiences are stronger when the same ecosystem helps them connect and move forward.': 'Organisateurs, artistes, salles, agents, marques et publics sont plus forts lorsqu’un même écosystème les aide à se connecter et à avancer.',
  'We are not trying to make events feel more digital. We are using technology to make discovery, access, and event operations simpler, so the experience itself can take over.': 'Notre objectif n’est pas de rendre les événements plus numériques. Nous utilisons la technologie pour simplifier la découverte, l’accès et l’organisation afin que l’expérience prenne toute sa place.',
  'Your event deserves': 'Votre événement mérite', 'a full house.': 'une salle comble.', 'Publish your event, sell tickets, manage access, understand your audience, and keep your attention where it belongs: on creating a great experience.': 'Publiez votre événement, vendez des billets, gérez les entrées, comprenez votre public et concentrez-vous sur l’essentiel : créer une expérience mémorable.',
  'Plan': 'Planifier', 'Sell': 'Vendre', 'Grow': 'Développer', 'Simple pricing': 'Des tarifs simples', 'Clear from the': 'Clair dès le', 'first ticket.': 'premier billet.', 'Straightforward tools and pricing designed to make professional event management more accessible to organizers in Burundi.': 'Des outils et des tarifs transparents pour rendre la gestion professionnelle d’événements plus accessible aux organisateurs du Burundi.',
  'Discover': 'Découvrir', 'Free': 'Gratuit', 'Find events and keep your tickets in one place.': 'Trouvez des événements et gardez vos billets au même endroit.', 'Host': 'Organiser', 'Built to grow': 'Conçu pour grandir', 'Tools for organizers to publish, sell, scan, manage, and understand their events.': 'Des outils pour publier, vendre, scanner, gérer et analyser vos événements.',
  'Questions': 'Questions', 'Good to': 'Bon à', 'know.': 'savoir.', 'Still curious? Here are a few answers to help you find your way around Tiketi.': 'Vous avez encore des questions ? Voici quelques réponses pour mieux utiliser Tiketi.', 'Get in touch': 'Nous contacter', 'Have something': 'Une idée', 'in mind?': 'en tête ?', 'Whether you are planning your first event, growing an event series, building a venue, looking for the next experience to attend, or want to work with Tiketi, we would love to hear from you.': 'Que vous prépariez votre premier événement, développiez une série, gériez une salle ou cherchiez une prochaine sortie, nous serions ravis d’échanger avec vous.',
  'Back to Tiketi': 'Retour à Tiketi', 'About Tiketi': 'À propos de Tiketi', 'Making events feel': 'Rendre les événements', 'closer.': 'plus proches.',
  'Our mission': 'Notre mission', 'Build the bridge between': 'Créer un lien entre', 'people and possibility.': 'les personnes et les possibles.', 'Great events already exist in every city. They should not be difficult to find, trust, or join. Tiketi connects audiences with the organizers, artists, venues, and communities making those moments happen.': 'Chaque ville regorge de grands événements. Ils ne devraient pas être difficiles à trouver, à choisir ni à rejoindre. Tiketi met le public en relation avec les organisateurs, artistes, salles et communautés qui les font vivre.',
  'Explore the Tiketi story': 'Découvrir l’histoire de Tiketi', 'Events discoverable': 'Événements à découvrir', 'For every ticket journey': 'Pour chaque parcours de billet', 'Where we begin': 'Là où tout commence', 'What guides us': 'Ce qui nous guide', 'Keep it clear': 'La clarté avant tout', 'Stay local': 'Rester proche du terrain', 'Make it count': 'Donner du sens',
  'Simple discovery, honest details, and a ticket people can find when they need it.': 'Une découverte simple, des informations fiables et un billet facile à retrouver.', 'Build for the people and rhythms of the places where the next experience starts.': 'Concevoir pour les personnes et les rythmes des lieux où naissent les expériences.', 'Give organizers the confidence to host well and audiences a reason to return.': 'Donner aux organisateurs les moyens de réussir et au public l’envie de revenir.',
  'What Tiketi makes possible': 'Ce que Tiketi rend possible', 'From first idea': 'De la première idée', 'to full room.': 'à la salle comble.', 'One connected platform keeps the important parts of an event moving together.': 'Une plateforme connectée coordonne les étapes essentielles de votre événement.', 'Find an event': 'Trouver un événement', 'Experience': 'Vivre', 'View my tickets': 'Voir mes billets', 'For organizers': 'Pour les organisateurs',
  'Clear answers when you need them.': 'Des réponses claires quand vous en avez besoin.', 'Support / Help Center': 'Assistance / Centre d’aide', 'Everything you need to know about finding events, buying tickets, managing your account, and hosting on Tiketi.': 'Tout ce qu’il faut savoir pour trouver des événements, acheter des billets, gérer votre compte et organiser sur Tiketi.',
  'Buying a ticket': 'Acheter un billet', 'Choose an event, select the ticket type that fits your plans, and continue through checkout. Once the payment clears, your tickets will appear in My Tickets and can be used whenever you are ready to attend.': 'Choisissez un événement, sélectionnez le billet qui vous convient et procédez au paiement. Une fois le paiement confirmé, vos billets apparaîtront dans Mes billets.',
  'Double-check the date, venue, and ticket type before paying.': 'Vérifiez la date, le lieu et le type de billet avant de payer.', 'Keep your confirmation ready when you arrive at the event.': 'Gardez votre confirmation à portée de main à votre arrivée.', 'If you need help with a specific event, contact the organizer listed on the event page.': 'Pour toute question sur un événement, contactez l’organisateur indiqué sur sa page.',
  'Managing your tickets': 'Gérer vos billets', 'Sign in to view upcoming and past tickets. Your purchase history is linked to the account used during checkout, so it is best to keep the same email and login details for your account.': 'Connectez-vous pour consulter vos billets à venir et passés. Votre historique d’achat est associé au compte utilisé lors du paiement.', 'View your active tickets in My Tickets.': 'Consultez vos billets actifs dans Mes billets.', 'Keep your QR code or confirmation available on your phone.': 'Gardez votre code QR ou votre confirmation sur votre téléphone.', 'Contact support if a ticket is missing or incorrect.': 'Contactez l’assistance si un billet manque ou comporte une erreur.',
  'For organizers': 'Pour les organisateurs', 'Organizer accounts can publish events, create ticket tiers, track sales, and manage guest check-in. Start from your dashboard and build your event listing in a few simple steps.': 'Les organisateurs peuvent publier des événements, créer des catégories de billets, suivre les ventes et gérer l’accueil. Commencez depuis votre tableau de bord.', 'Create your event page with clear details and pricing.': 'Créez une page d’événement avec des informations et des tarifs clairs.', 'Add the correct venue, date, and ticket options.': 'Indiquez le bon lieu, la date et les options de billet.', 'Use the organizer tools to monitor sales and guest check-in.': 'Utilisez les outils d’organisation pour suivre les ventes et les arrivées.',
  'Account and sign-in help': 'Compte et connexion', 'If you are having trouble signing in, check that you are using the same email you registered with. You can also use the password reset option if needed. Never share your login details with anyone else.': 'En cas de difficulté de connexion, vérifiez que vous utilisez l’adresse e-mail associée à votre compte. Vous pouvez aussi réinitialiser votre mot de passe. Ne partagez jamais vos identifiants.', 'Use the email connected to the account you created.': 'Utilisez l’adresse e-mail associée à votre compte.', 'Keep your password private and unique.': 'Gardez votre mot de passe secret et unique.', 'Contact Tiketi if you suspect an account or payment issue.': 'Contactez Tiketi en cas de problème de compte ou de paiement.',
  'Changes and event updates': 'Modifications et actualités des événements', 'Still need help?': 'Besoin d’aide supplémentaire ?', 'We are here to help.': 'Nous sommes là pour vous aider.', 'Support / Contact Us': 'Assistance / Contact', 'Support / Refunds': 'Assistance / Remboursements', 'Legal / Privacy': 'Juridique / Confidentialité', 'Legal / Terms of Service': 'Juridique / Conditions d’utilisation',
  'Back to events': 'Retour aux événements', 'Back to my tickets': 'Retour à mes billets', 'Event details': 'Détails de l’événement', 'Event check-in': 'Contrôle d’accès', 'Live ticket scanner': 'Scanner de billets en direct', 'Scan a valid ticket QR code to check guests in.': 'Scannez le code QR d’un billet valide pour enregistrer l’arrivée des invités.', 'Point camera at QR code': 'Pointez la caméra vers le code QR', 'Stop camera': 'Arrêter la caméra', 'Start QR camera': 'Activer le scanner QR', 'Or enter ticket number manually': 'Ou saisissez le numéro du billet', 'Use the QR code printed on the customer’s real ticket.': 'Utilisez le code QR figurant sur le billet du participant.', 'Check': 'Vérifier', 'Ticket Valid': 'Billet valide', 'Checked in successfully': 'Arrivée enregistrée', 'Guest': 'Invité', 'Ticket': 'Billet', 'Scan next': 'Scanner le suivant', 'Already Used': 'Déjà utilisé', 'Originally checked in:': 'Arrivée initialement enregistrée :', 'Previously': 'Précédemment', 'Name': 'Nom', 'Check-in Declined': 'Accès refusé', 'Check-in unavailable': 'Contrôle d’accès indisponible', 'Invalid Ticket': 'Billet invalide',
  'Camera access was blocked. Allow camera access in your browser settings, then try again.': 'L’accès à la caméra est bloqué. Autorisez-le dans les paramètres du navigateur, puis réessayez.', 'Validating…': 'Vérification…', 'checked in': 'arrivées enregistrées',
  'Your tickets': 'Vos billets', 'Your info': 'Vos informations', 'Payment': 'Paiement', 'Continue': 'Continuer', 'Back': 'Retour', 'Full name': 'Nom complet', 'Phone number': 'Numéro de téléphone', 'Email address': 'Adresse e-mail', 'Name on ticket': 'Nom sur le billet', 'Mobile Money number': 'Numéro Mobile Money', 'Mobile Money': 'Mobile Money', 'Card': 'Carte', 'Pay now': 'Payer maintenant', 'Order summary': 'Récapitulatif de la commande', 'Subtotal': 'Sous-total', 'Service fee': 'Frais de service', 'Total': 'Total', 'Secure checkout': 'Paiement sécurisé', 'Ticket holder': 'Titulaire du billet', 'Enter your full name.': 'Saisissez votre nom complet.', 'Enter a valid phone number.': 'Saisissez un numéro de téléphone valide.', 'Enter a valid email address.': 'Saisissez une adresse e-mail valide.', 'Enter a name for every ticket holder.': 'Saisissez le nom de chaque titulaire de billet.', 'Choose a valid quantity.': 'Choisissez une quantité valide.',
  'My Tickets': 'Mes billets', 'Upcoming': 'À venir', 'Past': 'Passés', 'Cancelled': 'Annulé', 'No upcoming events yet.': 'Aucun événement à venir.', 'Try again': 'Réessayer', 'No notifications yet': 'Aucune notification pour le moment', 'When there are updates about your tickets, events, or payments, you will see them here.': 'Les actualités concernant vos billets, événements ou paiements s’afficheront ici.', 'All': 'Tout', 'Offers': 'Offres', 'Team': 'Équipe', 'Mark all read': 'Tout marquer comme lu', 'unread': 'non lues',
  'Sign in to see notifications': 'Connectez-vous pour voir vos notifications', 'Sign in to view your profile': 'Connectez-vous pour voir votre profil', 'Sign in to view your tickets': 'Connectez-vous pour voir vos billets', 'Sign in to continue': 'Connectez-vous pour continuer', 'Create an account to keep going.': 'Créez un compte pour continuer.', 'Required': 'Obligatoire', 'Later': 'Plus tard', 'Sign in to save events': 'Connectez-vous pour enregistrer des événements', 'Create an account to bookmark events you love.': 'Créez un compte pour ajouter vos événements préférés.', 'Sign in to follow organizers': 'Connectez-vous pour suivre des organisateurs', 'Create an account to follow your favorite event hosts and get updates from them.': 'Créez un compte pour suivre vos organisateurs préférés et recevoir leurs actualités.',
  'Account': 'Compte', 'Attendee': 'Participant', 'Organizer': 'Organisateur', 'Team member': 'Membre de l’équipe', 'Attendees': 'Participants', 'Email notifications': 'Notifications par e-mail', 'Event reminders': 'Rappels d’événement', 'Promotions': 'Promotions', 'Nearby events': 'Événements à proximité', 'Preferences': 'Préférences', 'Security': 'Sécurité', 'Save changes': 'Enregistrer les modifications', 'Save': 'Enregistrer', 'Saving…': 'Enregistrement…', 'Saved': 'Enregistré', 'Password': 'Mot de passe', 'Confirm password': 'Confirmer le mot de passe', 'Current password': 'Mot de passe actuel', 'New password': 'Nouveau mot de passe', 'Update password': 'Mettre à jour le mot de passe', 'Upload image': 'Importer une image', 'Change photo': 'Changer la photo', 'Remove image': 'Supprimer l’image',
  'Overview': 'Vue d’ensemble', 'Users': 'Utilisateurs', 'Organizers': 'Organisateurs', 'Orders': 'Commandes', 'Payments': 'Paiements', 'Payouts': 'Versements', 'Ticket agents': 'Agents de billetterie', 'Reports': 'Rapports', 'Platform settings': 'Paramètres de la plateforme', 'Analytics': 'Analyses', 'Customers': 'Clients', 'Followers': 'Abonnés', 'Members': 'Membres', 'Roles': 'Rôles', 'Transactions': 'Transactions', 'Refund requests': 'Demandes de remboursement', 'Assigned Events': 'Événements attribués', 'Sell Tickets': 'Vendre des billets', 'Sales': 'Ventes', 'Commissions': 'Commissions', 'Wallet': 'Portefeuille', 'Withdrawals': 'Retraits', 'View all': 'Tout afficher', 'Last updated': 'Dernière mise à jour', 'All time': 'Depuis toujours', 'Select dates': 'Sélectionner des dates',
  'Sign in to access the dashboard': 'Connectez-vous pour accéder au tableau de bord', 'Sign in as Organizer': 'Se connecter comme organisateur', 'Loading your dashboard…': 'Chargement de votre tableau de bord…', 'Organizer access required': 'Accès organisateur requis', 'This account is not registered as an organizer.': 'Ce compte n’est pas inscrit comme organisateur.', 'Go Home': 'Accueil', 'Sign in to access admin tools': 'Connectez-vous pour accéder aux outils d’administration', 'Admin access required.': 'Accès administrateur requis.', 'This account does not have platform admin privileges.': 'Ce compte ne dispose pas des droits d’administration de la plateforme.', 'Sign in to access agent tools': 'Connectez-vous pour accéder aux outils de l’agent', 'Agent access required.': 'Accès agent requis.', 'This account does not have an active agent assignment.': 'Ce compte n’a aucune affectation d’agent active.',
  'No tickets selected': 'Aucun billet sélectionné', 'Unable to load this event': 'Impossible de charger cet événement', 'Loading event...': 'Chargement de l’événement…', 'Please wait while we load the event details.': 'Veuillez patienter pendant le chargement des détails de l’événement.', 'Browse Events': 'Parcourir les événements', 'Unable to load this organizer': 'Impossible de charger cet organisateur', 'Loading organizer...': 'Chargement de l’organisateur…', 'Please wait while we load the organizer profile.': 'Veuillez patienter pendant le chargement du profil de l’organisateur.', 'Browse organizers': 'Parcourir les organisateurs', 'The marketplace is temporarily unavailable': 'La place de marché est temporairement indisponible', 'We’ll be back shortly': 'Nous serons bientôt de retour', 'Need help?': 'Besoin d’aide ?', 'View my tickets': 'Voir mes billets',
  'Share this event': 'Partager cet événement', 'Share organizer': 'Partager le profil de l’organisateur', 'Send it to someone who would love it.': 'Partagez-le avec quelqu’un qui l’appréciera.', 'Close share dialog': 'Fermer la fenêtre de partage', 'Close share sheet': 'Fermer le panneau de partage', 'Copy link': 'Copier le lien', 'Copied': 'Copié', 'Copied!': 'Copié !', 'Share event': 'Partager l’événement', 'Share': 'Partager', 'WhatsApp': 'WhatsApp', 'Facebook': 'Facebook', 'Instagram': 'Instagram',
  'Save event': 'Enregistrer l’événement', 'Remove event from favorites': 'Retirer l’événement des favoris', 'Follow': 'Suivre', 'Following': 'Abonné', 'Your profile': 'Votre profil', 'View Profile': 'Voir le profil', 'Saving…': 'Enregistrement…', 'Event details': 'Détails de l’événement', 'Date': 'Date', 'Time': 'Heure', 'Venue': 'Lieu', 'Location': 'Emplacement', 'View on map': 'Voir sur la carte', 'About this event': 'À propos de cet événement', 'Get tickets': 'Obtenir des billets', 'Choose your ticket type to continue': 'Choisissez votre type de billet pour continuer', 'Tickets will be available soon.': 'Les billets seront bientôt disponibles.', 'Tickets are non-refundable': 'Les billets ne sont pas remboursables', 'Valid ID required at entry': 'Une pièce d’identité valide est requise à l’entrée', 'Questions about tickets?': 'Des questions sur les billets ?', 'Contact the organizer.': 'Contactez l’organisateur.', 'Related events': 'Événements similaires', 'Event ended': 'Événement terminé', 'Free entry': 'Entrée gratuite', 'View all': 'Tout afficher', 'Copied': 'Copié',
  'No events found.': 'Aucun événement trouvé.', 'No organizers found.': 'Aucun organisateur trouvé.', 'Unable to load organizers right now. Please try again.': 'Impossible de charger les organisateurs pour le moment. Veuillez réessayer.', 'Community directory': 'Annuaire communautaire', 'Made for following.': 'À suivre de près.', 'The people behind the plans': 'Les personnes derrière les projets', 'Follow the teams shaping the city’s best nights, gatherings and ideas.': 'Suivez les équipes qui façonnent les meilleures soirées, rencontres et idées de la ville.', 'creators': 'créateurs',
  'You’re in!': 'C’est confirmé !', 'Your ticket has been confirmed. See you there.': 'Votre billet est confirmé. À bientôt !', 'This ticket is': 'Ce billet est', 'VALID': 'VALIDE', 'USED': 'UTILISÉ', 'CANCELLED': 'ANNULÉ', 'EXPIRED': 'EXPIRÉ', 'SCAN TO ENTER': 'SCANNER POUR ENTRER', 'Ticket code unavailable': 'Code du billet indisponible', 'PDF ticket downloaded.': 'Billet PDF téléchargé.', 'Unable to create the PDF ticket.': 'Impossible de créer le billet PDF.', 'Choose WhatsApp, email, or another app to send the PDF.': 'Choisissez WhatsApp, e-mail ou une autre application pour envoyer le PDF.', 'PDF sharing is unavailable here. Ticket details copied instead.': 'Le partage du PDF est indisponible. Les détails du billet ont été copiés.', 'Ticket sharing was cancelled.': 'Le partage du billet a été annulé.', 'Ticket type': 'Type de billet', 'Ticket holder': 'Titulaire du billet', 'Date': 'Date', 'Venue': 'Lieu', 'Powered by Tiketi': 'Propulsé par Tiketi',
  'Good evening': 'Bonsoir', 'Unknown event': 'Événement inconnu', 'Publish an event to see performance here': 'Publiez un événement pour voir ses résultats ici', 'Create a sale to see event performance': 'Créez une vente pour voir les résultats de l’événement', 'Revenue trend for the last seven days': 'Évolution des revenus sur les sept derniers jours',
  'We couldn’t load your tickets.': 'Impossible de charger vos billets.', 'No upcoming events.': 'Aucun événement à venir.', 'No past events yet.': 'Aucun événement passé.', 'No cancelled tickets.': 'Aucun billet annulé.', 'No upcoming tickets': 'Aucun billet à venir', 'No past tickets': 'Aucun billet passé', 'No cancelled tickets': 'Aucun billet annulé', 'You don’t have any upcoming events. Browse and get your first ticket!': 'Vous n’avez aucun événement à venir. Parcourez les événements et obtenez votre premier billet !', 'Try again': 'Réessayer', 'View QR': 'Afficher le QR', 'Hide QR': 'Masquer le QR', 'View ticket': 'Voir le billet', 'Refund request:': 'Demande de remboursement :', 'Under review': 'En cours d’examen', 'Approved for processing': 'Approuvé pour traitement', 'Processed': 'Traité', 'Declined': 'Refusé',
  'What is Tiketi?': 'Qu’est-ce que Tiketi ?', 'We are here to help.': 'Nous sommes là pour vous aider.', 'Last updated:': 'Dernière mise à jour :', 'Need a person?': 'Besoin de parler à quelqu’un ?', 'Our support team is ready to help with your next question.': 'Notre équipe d’assistance est prête à répondre à vos questions.', 'Email Tiketi': 'Écrire à Tiketi', 'We reply within 24-48 hours': 'Nous répondons sous 24 à 48 heures',
  'Application': 'Candidature', 'No favorites yet': 'Aucun favori pour le moment', 'Save events you love to find them here.': 'Enregistrez vos événements préférés pour les retrouver ici.', 'Explore events': 'Explorer les événements', 'No saved events yet': 'Aucun événement enregistré',
  'Sign in to view your tickets': 'Connectez-vous pour voir vos billets', 'Sign in to access your account': 'Connectez-vous pour accéder à votre compte',
  'Enter your email.': 'Saisissez votre adresse e-mail.', 'Fill in all fields.': 'Veuillez remplir tous les champs.', 'Incorrect email or password. Please try again.': 'Adresse e-mail ou mot de passe incorrect. Veuillez réessayer.', 'Check your inbox and click the confirmation link, then try signing in again.': 'Consultez votre boîte de réception et cliquez sur le lien de confirmation, puis réessayez de vous connecter.', 'An account with this email already exists. Sign in instead.': 'Un compte associé à cette adresse existe déjà. Connectez-vous plutôt.', 'Password must be at least 6 characters.': 'Le mot de passe doit contenir au moins 6 caractères.', 'Password must be at least 8 characters.': 'Le mot de passe doit contenir au moins 8 caractères.', 'Passwords do not match.': 'Les mots de passe ne correspondent pas.', 'Too many attempts. Wait a moment and try again.': 'Trop de tentatives. Patientez un instant avant de réessayer.', 'Something went wrong. Please try again.': 'Une erreur s’est produite. Veuillez réessayer.', 'Account created! Check your email to confirm, then sign in.': 'Compte créé ! Consultez votre e-mail pour confirmer votre adresse, puis connectez-vous.', 'Reset link sent — check your inbox.': 'Lien de réinitialisation envoyé : consultez votre boîte de réception.', 'Google sign-in is not fully configured. In your Supabase dashboard go to Authentication → Providers → Google and add your Google OAuth Client ID and Client Secret. Use email/password below instead.': 'La connexion Google n’est pas entièrement configurée. Dans Supabase, ouvrez Authentication → Providers → Google et ajoutez vos identifiants OAuth Google. Vous pouvez utiliser l’e-mail et le mot de passe ci-dessous.', 'Email sign-in is not enabled. In your Supabase dashboard go to Authentication → Providers and enable the Email provider.': 'La connexion par e-mail n’est pas activée. Dans Supabase, ouvrez Authentication → Providers et activez le fournisseur e-mail.',
  'For Organizers': 'Pour les organisateurs', 'Event Discovery': 'Découverte d’événements', 'Sell out your': 'Faites salle comble pour', 'next event.': 'votre prochain événement.', 'Discover events': 'Découvrir des événements', 'near you.': 'près de chez vous.', 'Create, sell, promote and manage events from one platform built for Burundi.': 'Créez, vendez, faites la promotion et gérez vos événements depuis une plateforme conçue pour le Burundi.', 'Find concerts, parties, sports, comedy and more happening in Bujumbura.': 'Trouvez les concerts, soirées, événements sportifs, spectacles d’humour et bien plus à Bujumbura.', 'Sell tickets online and through agents': 'Vendez des billets en ligne et par l’intermédiaire d’agents', 'Real-time sales analytics & revenue': 'Analyses des ventes et revenus en temps réel', 'QR check-in and attendee management': 'Contrôle par QR et gestion des participants', 'I am a': 'Je suis', 'Sign in': 'Se connecter', 'Sign up': 'S’inscrire', 'Forgot password?': 'Mot de passe oublié ?', 'Continue with Google': 'Continuer avec Google', 'Or continue with email': 'Ou continuer avec une adresse e-mail',
  'Something went wrong. Please try again.': 'Une erreur s’est produite. Veuillez réessayer.',
}

Object.assign(fr, frSupplement)
Object.assign(fr, publicFr, accountFr, dashboardFr, miscFr)

function getInitialLanguage(): 'en' | 'fr' {
  try {
    const savedLanguage = window.localStorage.getItem('tiketi-language')
    if (savedLanguage === 'en' || savedLanguage === 'fr') return savedLanguage
  } catch {
    // Browser storage can be disabled; fall back to the browser language.
  }

  const browserLanguage = navigator.languages?.[0] ?? navigator.language ?? 'en'
  return browserLanguage.toLowerCase().startsWith('fr') ? 'fr' : 'en'
}

i18n
  .init({
    lng: getInitialLanguage(),
    resources: { en: { translation: {} }, fr: { translation: fr } },
    fallbackLng: 'en',
    supportedLngs: ['en', 'fr'],
    load: 'languageOnly',
    nonExplicitSupportedLngs: true,
    keySeparator: false,
    interpolation: { escapeValue: false },
  })

function syncDocumentLocale(language = i18n.resolvedLanguage ?? 'en') {
  const lang = language.toLowerCase().startsWith('fr') ? 'fr' : 'en'
  document.documentElement.lang = lang
  const title = lang === 'fr' ? 'Tiketi | Découvrez. Réservez. Vivez.' : 'Tiketi | Discover. Book. Experience.'
  document.title = title
  document.querySelector('meta[property="og:title"]')?.setAttribute('content', title)
  document.querySelector('meta[name="description"]')?.setAttribute('content', lang === 'fr' ? 'Découvrez, réservez et vivez des événements au Burundi avec Tiketi.' : 'Discover, book, and experience events in Burundi with Tiketi.')
  document.querySelector('meta[property="og:description"]')?.setAttribute('content', lang === 'fr' ? 'Découvrez, réservez et vivez des événements au Burundi avec Tiketi.' : 'Discover, book, and experience events in Burundi with Tiketi.')
}

i18n.on('languageChanged', syncDocumentLocale)
syncDocumentLocale()

export default i18n
