const frSupplement: Record<string, string> = {
  'Back to events': 'Retour aux événements', 'Back to my tickets': 'Retour à mes billets', 'Event details': 'Détails de l’événement', 'Discover events': 'Découvrir les événements', 'Meet the organizers': 'Rencontrez les organisateurs', 'People behind the events': 'Les personnes derrière les événements',
  'The home for Burundi’s live culture': 'Le foyer de la culture vivante du Burundi', 'Moments worth': 'Des moments qui méritent', 'showing up for.': 'qu’on se déplace.', 'The home for Burundi\'s live culture': 'Le foyer de la culture vivante du Burundi',
  'About Tiketi': 'À propos de Tiketi', 'Making events feel': 'Rendre les événements', 'closer.': 'plus proches.', 'Our mission': 'Notre mission', 'Build the bridge between': 'Créer un lien entre', 'people and possibility.': 'les personnes et les possibles.', 'What guides us': 'Ce qui nous guide', 'What Tiketi makes possible': 'Ce que Tiketi rend possible',
  'Clear answers when you need them.': 'Des réponses claires quand vous en avez besoin.', 'Support / Help Center': 'Assistance / Centre d’aide', 'Support / Contact Us': 'Assistance / Nous contacter', 'Support / Refunds': 'Assistance / Remboursements', 'Legal / Terms of Service': 'Juridique / Conditions d’utilisation', 'Legal / Privacy': 'Juridique / Confidentialité',
  'Everything you need to know about finding events, buying tickets, managing your account, and hosting on Tiketi.': 'Tout ce qu’il faut savoir pour trouver des événements, acheter des billets, gérer votre compte et organiser sur Tiketi.', 'We are here to help.': 'Nous sommes là pour vous aider.', 'Whether you are attending your first event or building your next one, our team is ready to help with the next step.': 'Que vous assistiez à votre premier événement ou prépariez le prochain, notre équipe est là pour vous aider.', 'Simple, fair, and clear refund support.': 'Une assistance remboursement simple, juste et claire.',
  'Buying a ticket': 'Acheter un billet', 'Managing your tickets': 'Gérer vos billets', 'For organizers': 'Pour les organisateurs', 'Account and sign-in help': 'Compte et connexion', 'Changes and event updates': 'Modifications et actualités des événements', 'Still need help?': 'Besoin d’aide supplémentaire ?', 'General support': 'Assistance générale', 'Questions about an event': 'Questions sur un événement', 'Organizer partnerships': 'Partenariats avec les organisateurs', 'Report a safety or platform issue': 'Signaler un problème de sécurité ou de plateforme', 'Press and community': 'Presse et communauté',
  'Acceptance and eligibility': 'Acceptation et admissibilité', 'Accounts and responsibilities': 'Comptes et responsabilités', 'Events and organizer content': 'Événements et contenu des organisateurs', 'Tickets, payments, and entry': 'Billets, paiements et accès', 'Prohibited activities': 'Activités interdites', 'Content and intellectual property': 'Contenu et propriété intellectuelle', 'Third-party services': 'Services tiers', 'Suspension and termination': 'Suspension et résiliation', 'Availability and liability': 'Disponibilité et responsabilité', 'Changes and contact': 'Modifications et contact',
  'Information you provide': 'Informations que vous fournissez', 'Information we collect automatically': 'Informations recueillies automatiquement', 'How we use information': 'Utilisation des informations', 'Event and organizer sharing': 'Partage avec les organisateurs', 'Service providers and payments': 'Prestataires et paiements', 'Cookies and local storage': 'Cookies et stockage local', 'Retention and security': 'Conservation et sécurité', 'Your choices and deletion requests': 'Vos choix et demandes de suppression', 'Children and third-party links': 'Mineurs et liens tiers', 'Legal disclosures and changes': 'Divulgations légales et modifications',
  'Before you buy': 'Avant votre achat', 'If an event changes': 'En cas de modification d’un événement', 'How to request help': 'Comment demander de l’aide', 'Processing time': 'Délais de traitement', 'What may not be refundable': 'Ce qui peut ne pas être remboursable', 'Organizer responsibility': 'Responsabilité de l’organisateur',
  'Clear answers when you need them.': 'Des réponses claires quand vous en avez besoin.', 'The rules that keep Tiketi fair and reliable.': 'Les règles qui rendent Tiketi équitable et fiable.', 'Your information stays protected.': 'Vos informations restent protégées.', 'Simple, fair, and clear refund support.': 'Une assistance remboursement simple, juste et claire.',
  'Sign in to continue': 'Connectez-vous pour continuer', 'Create an account to reserve tickets and manage your event purchases.': 'Créez un compte pour réserver des billets et gérer vos achats d’événements.', 'Create an account to keep going.': 'Créez un compte pour continuer.', 'Sign in to save events': 'Connectez-vous pour enregistrer des événements', 'Create an account to bookmark events you love.': 'Créez un compte pour ajouter vos événements préférés.', 'Sign in to follow organizers': 'Connectez-vous pour suivre des organisateurs', 'Create an account to follow your favorite event hosts and get updates from them.': 'Créez un compte pour suivre vos organisateurs préférés et recevoir leurs actualités.',
  'Sign in to view your profile': 'Connectez-vous pour voir votre profil', 'Sign in to view your tickets': 'Connectez-vous pour voir vos billets', 'Sign in to see notifications': 'Connectez-vous pour voir vos notifications', 'Sign in to access the dashboard': 'Connectez-vous pour accéder au tableau de bord', 'Organizer access required': 'Accès organisateur requis', 'Admin access required.': 'Accès administrateur requis.', 'Agent access required.': 'Accès agent requis.', 'This account is not registered as an organizer.': 'Ce compte n’est pas inscrit comme organisateur.', 'This account does not have platform admin privileges.': 'Ce compte ne dispose pas des droits d’administration de la plateforme.', 'This account does not have an active agent assignment.': 'Ce compte n’a aucune affectation d’agent active.',
  'Your tickets': 'Vos billets', 'Your info': 'Vos informations', 'Order summary': 'Récapitulatif de la commande', 'Subtotal': 'Sous-total', 'Service fee': 'Frais de service', 'Total': 'Total', 'Secure checkout': 'Paiement sécurisé', 'Select tickets': 'Sélectionner les billets', 'Continue to payment': 'Continuer vers le paiement', 'Complete purchase': 'Finaliser l’achat', 'Payment successful': 'Paiement effectué', 'Payment method': 'Mode de paiement', 'Mobile Money payments are currently unavailable.': 'Les paiements Mobile Money sont actuellement indisponibles.', 'Card payments are currently unavailable.': 'Les paiements par carte sont actuellement indisponibles.', 'Ticket sales are currently paused. Please try again later.': 'La vente de billets est momentanément suspendue. Veuillez réessayer plus tard.', 'Enter the mobile money number that should receive the payment prompt.': 'Saisissez le numéro Mobile Money qui recevra la demande de paiement.',
  'Enter your full name.': 'Saisissez votre nom complet.', 'Enter a valid phone number.': 'Saisissez un numéro de téléphone valide.', 'Enter a valid email address.': 'Saisissez une adresse e-mail valide.', 'Enter a name for every ticket holder.': 'Saisissez le nom de chaque titulaire de billet.', 'Choose a valid quantity.': 'Choisissez une quantité valide.', 'No tickets selected': 'Aucun billet sélectionné',
  'Dashboard overview': 'Vue d’ensemble du tableau de bord', 'Total Events': 'Nombre total d’événements', 'Tickets Sold': 'Billets vendus', 'Active Organizers': 'Organisateurs actifs', 'Active Users': 'Utilisateurs actifs', 'Gross ticket value': 'Valeur brute des billets', 'Platform revenue': 'Revenus de la plateforme', 'New signups today': 'Nouvelles inscriptions aujourd’hui', 'Repeat buyers': 'Acheteurs récurrents', 'Admin accounts': 'Comptes administrateur', 'Awaiting verification': 'En attente de vérification', 'Published events': 'Événements publiés', 'Draft events': 'Événements en brouillon', 'Listed capacity': 'Capacité totale', 'Low inventory alerts': 'Alertes de stock bas', 'Scans today': 'Scans aujourd’hui', 'Cancelled tickets': 'Billets annulés', 'Confirmed orders': 'Commandes confirmées', 'Pending orders': 'Commandes en attente', 'Successful payments': 'Paiements réussis', 'Failed payments': 'Paiements échoués', 'Pending reconciliation': 'Rapprochements en attente', 'Active agents': 'Agents actifs', 'Verification requests': 'Demandes de vérification',
  'No events available': 'Aucun événement disponible', 'No events found': 'Aucun événement trouvé', 'No events found.': 'Aucun événement trouvé.', 'No organizers found.': 'Aucun organisateur trouvé.', 'No notifications yet': 'Aucune notification pour le moment', 'No saved events yet': 'Aucun événement enregistré', 'No upcoming events yet.': 'Aucun événement à venir pour le moment.', 'Try again': 'Réessayer', 'Unable to load this event': 'Impossible de charger cet événement', 'Loading event...': 'Chargement de l’événement…', 'Unable to load this organizer': 'Impossible de charger cet organisateur', 'Loading organizer...': 'Chargement de l’organisateur…', 'Loading events...': 'Chargement des événements…',
  'Choose language': 'Choisir la langue', 'English': 'Anglais', 'French': 'Français', 'Close navigation menu': 'Fermer le menu de navigation', 'Open navigation menu': 'Ouvrir le menu de navigation', 'Back to Tiketi': 'Retour à Tiketi', 'Last updated:': 'Dernière mise à jour :', 'Need a person?': 'Besoin de parler à quelqu’un ?', 'Our support team is ready to help with your next question.': 'Notre équipe d’assistance est prête à répondre à vos questions.', 'Email Tiketi': 'Écrire à Tiketi', 'We reply within 24-48 hours': 'Nous répondons sous 24 à 48 heures',
  'No event details available.': 'Aucun détail sur l’événement.', 'Browse Events': 'Parcourir les événements', 'Browse organizers': 'Parcourir les organisateurs', 'Browse all events': 'Voir tous les événements', 'View all organizers': 'Voir tous les organisateurs', 'Try different filters or search terms.': 'Essayez d’autres filtres ou termes de recherche.', 'Clear filters': 'Effacer les filtres', 'Clear all': 'Tout effacer', 'Filters': 'Filtres', 'Search events, artists, venues…': 'Rechercher des événements, artistes, lieux…', 'Search organizers': 'Rechercher des organisateurs',
}

export default frSupplement
