import { useEffect, useState } from 'react'
import { ArrowRightIcon, BarChartIcon, CheckIcon, ChevronDownIcon, ClipboardIcon, DollarSignIcon, LinkIcon, QrCodeIcon, TicketIcon, UsersIcon, ZapIcon } from '../components/Icon'
import { events } from '../data/events'

type Props = { navigate: (page: string) => void }

const heroEvent = events[0]
const logos = Array.from(new Set(events.map(event => event.organizer))).slice(0, 8)
const formatBif = (value: number) => `BIF ${value.toLocaleString()}`
const faqs = [
  ['How can I create an event?', 'Create an organizer account, enter your event details, add ticket types and pricing, review the listing, and publish when it is ready.'],
  ['Do I need a computer?', 'Tiketi Studio should work comfortably on mobile for important event tasks. Confirm feature parity across mobile and desktop before launch.'],
  ['What payment methods are supported?', 'Publish the exact mobile-money, card, bank, and other methods once they are confirmed.'],
  ['How do I cash out?', 'Withdrawals depend on settlement status, available balance, payment method, and Tiketi\'s terms. Publish exact timing once finalized.'],
  ['What events can I host?', 'Music, nightlife, sports, conferences, culture, comedy, student events, community gatherings, workshops, and other legitimate experiences that meet Tiketi\'s policies.'],
]

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  return <div className={`organizer-reference-reveal ${className}`}>{children}</div>
}

function Phone({ variant, label }: { variant: 'dashboard' | 'create' | 'payout' | 'withdraw' | 'analytics' | 'guests'; label: string }) {
  const sold = heroEvent.ticketsSold.toLocaleString()
  const revenue = formatBif(heroEvent.ticketsSold * heroEvent.price)
  return <div className={`organizer-reference-phone organizer-tiketi-phone-${variant}`} role="img" aria-label={label}>
    <div className="organizer-reference-notch" />
    <div className="organizer-tiketi-status"><span>9:41</span><span>● ● ▰</span></div>
    <div className="organizer-tiketi-appbar"><b>{variant === 'create' ? 'New event' : variant === 'payout' || variant === 'withdraw' ? 'Wallet' : variant === 'analytics' ? 'Insights' : variant === 'guests' ? 'Guest list' : 'Tiketi Studio'}</b><span>•••</span></div>
    {variant === 'dashboard' && <><div className="organizer-tiketi-greeting">Good evening, BJ Events</div><div className="organizer-tiketi-event-banner"><span>LIVE EVENT</span><b>{heroEvent.name}</b><small>{heroEvent.venue} · {heroEvent.date}</small></div><div className="organizer-tiketi-mini-grid"><span><b>{sold}</b><small>Tickets sold</small></span><span><b>{revenue}</b><small>Sales value</small></span></div><div className="organizer-tiketi-progress"><span><i style={{ width: `${Math.round((heroEvent.ticketsSold / heroEvent.capacity) * 100)}%` }} /></span><small>{Math.round((heroEvent.ticketsSold / heroEvent.capacity) * 100)}% of capacity</small></div></>}
    {variant === 'create' && <><div className="organizer-tiketi-form-image"><TicketIcon size={24} /><span>Add event cover</span></div><b className="organizer-tiketi-form-title">{heroEvent.name}</b><div className="organizer-tiketi-form-row"><span>Category</span><b>{heroEvent.category}</b></div><div className="organizer-tiketi-form-row"><span>City</span><b>{heroEvent.city}</b></div><div className="organizer-tiketi-form-row"><span>Capacity</span><b>{heroEvent.capacity.toLocaleString()}</b></div><button className="organizer-tiketi-screen-button">Publish event</button></>}
    {variant === 'payout' && <><div className="organizer-tiketi-balance-label">Available balance</div><strong className="organizer-tiketi-balance">BIF 2,480,000</strong><div className="organizer-tiketi-payout-card"><span>From ticket sales</span><b>{revenue}</b><small>Updated just now</small></div><button className="organizer-tiketi-screen-button">Withdraw earnings</button></>}
    {variant === 'withdraw' && <><div className="organizer-tiketi-balance-label">Withdraw to</div><div className="organizer-tiketi-momo"><b>Mobile Money</b><span>+257 79 000 000</span></div><div className="organizer-tiketi-form-row"><span>Amount</span><b>BIF 350,000</b></div><button className="organizer-tiketi-screen-button">Confirm withdrawal</button></>}
    {variant === 'analytics' && <><div className="organizer-tiketi-chart-label">Sales this week <b>+24.8%</b></div><div className="organizer-tiketi-chart"><i /><i /><i /><i /><i /><i /><i /></div><div className="organizer-tiketi-mini-grid"><span><b>{sold}</b><small>Scanned</small></span><span><b>{heroEvent.capacity.toLocaleString()}</b><small>Capacity</small></span></div></>}
    {variant === 'guests' && <><div className="organizer-tiketi-scan-card"><QrCodeIcon size={32} /><b>Scan to check in</b><small>Fast entry at Stade Intwari</small></div>{['Aline N.', 'Kevin M.', 'Diane K.'].map((guest, index) => <div className="organizer-tiketi-guest" key={guest}><span>{guest}</span><b>{index === 0 ? 'Checked in' : 'Ready'}</b></div>)}</>}
  </div>
}

function ProductTitle({ number, title }: { number: string; title: string }) {
  const accents: Record<string, string> = { '01': 'proper place.', '02': 'every sale.', '03': 'inside.' }
  const accent = accents[number] ?? ''
  const base = accent ? title.replace(accent, '').trimEnd() : title
  return <h2>{base}{accent && <> <em>{accent}</em></>}</h2>
}

function ProductSection({ number, label, title, copy, points, image, secondaryImage, reverse = false, navigate }: { number: string; label: string; title: string; copy: string; points: string[]; image: 'dashboard' | 'create' | 'payout' | 'withdraw' | 'analytics' | 'guests'; secondaryImage: 'dashboard' | 'create' | 'payout' | 'withdraw' | 'analytics' | 'guests'; reverse?: boolean; navigate: (page: string) => void }) {
  return <Reveal className={`organizer-reference-product ${reverse ? 'is-reversed' : ''}`}><div className="organizer-reference-product-copy"><p className="organizer-reference-kicker"><span>{number}</span> · {label}</p><ProductTitle number={number} title={title} /><p>{copy}</p><ul>{points.map(point => <li key={point}><CheckIcon size={15} />{point}</li>)}</ul><button onClick={() => navigate('auth-organizer')} className="organizer-reference-text-button organizer-reference-product-cta">Build your event <ArrowRightIcon size={15} /></button></div><div className="organizer-reference-phone-pair"><Phone variant={image} label={title} /><Phone variant={secondaryImage} label={`${title} detail`} /></div></Reveal>
}

export default function OrganizersPage({ navigate }: Props) {
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible') }), { threshold: .14 })
    const elements = document.querySelectorAll('.organizer-reference-reveal')
    elements.forEach(element => observer.observe(element))
    return () => observer.disconnect()
  }, [])

  return <main className="organizer-reference-page">
    <section className="organizer-reference-hero"><div className="organizer-reference-grid" /><div className="organizer-reference-shell organizer-reference-hero-inner"><div className="organizer-reference-hero-copy"><p className="organizer-reference-kicker"><ZapIcon size={15} /> Tiketi Studio for organizers</p><h1>Turn your next idea into a <em>full room.</em></h1><p>Plan the details, sell tickets in Burundian francs, manage your event team, and welcome every guest from one connected workspace.</p><div className="organizer-reference-actions"><button onClick={() => navigate('auth-organizer')}>Create an event <ArrowRightIcon size={16} /></button><a href="#pricing">View pricing</a></div><div className="organizer-reference-proof"><div><b>{heroEvent.capacity.toLocaleString()}</b><span>Capacity on a sample event</span></div><div><b>{heroEvent.ticketsSold.toLocaleString()}</b><span>Tickets sold</span></div><div><b>{heroEvent.city}</b><span>Built for Burundi organizers</span></div></div><div className="organizer-reference-hero-points"><span><ClipboardIcon size={18} /><b>Shape the listing</b><small>Publish the cover, details, tickets, and policies.</small></span><span><QrCodeIcon size={18} /><b>Keep entry moving</b><small>Scan guests and see who has arrived.</small></span><span><DollarSignIcon size={18} /><b>Know your money</b><small>Track sales and balance in BIF.</small></span></div></div><div className="organizer-reference-hero-visual"><div className="organizer-reference-hero-glow" /><Phone variant="dashboard" label="Tiketi Studio dashboard for Bujumbura Summer Fest" /></div></div></section>

    <section className="organizer-reference-trust"><div className="organizer-reference-shell"><p>Organizers building what&apos;s next with Tiketi</p><div className="organizer-reference-marquee"><div className="organizer-reference-marquee-track">{[...logos, ...logos].map((logo, index) => <span key={`${logo}-${index}`}><i>{logo.slice(0, 1)}</i>{logo}</span>)}</div></div></div></section>

    <section className="organizer-reference-shell organizer-reference-products"><div className="organizer-reference-section-intro"><p className="organizer-reference-kicker"><ZapIcon size={15} /> One toolkit, many moving parts</p><h2>Make the work feel<br /><em>lighter.</em></h2><p>Tiketi keeps the operational details close, so your attention can stay on the experience and the people you're bringing together.</p></div><ProductSection navigate={navigate} number="01" label="PUBLISH" title="Give the idea a proper place." copy="Build a clear event page with the cover, venue, category, capacity, ticket tiers, and the details guests need before they commit." points={['Use your own event image and voice', 'Set regular, VIP, VVIP, or custom ticket tiers', 'Update the page when plans change', 'Share one link across Instagram, WhatsApp, and other channels']} image="create" secondaryImage="dashboard" /><ProductSection navigate={navigate} reverse number="02" label="SETTLE" title="See the value of every sale." copy="Keep ticket revenue understandable from the first BIF sale through your available balance and eventual withdrawal." points={['Revenue shown in BIF', 'Separate ticket income from withdrawals', 'See the balance available to move', 'Keep a record of transactions']} image="payout" secondaryImage="withdraw" /><ProductSection navigate={navigate} number="03" label="WELCOME" title="Know who made it inside." copy="When the doors open, your team can focus on people rather than paper lists. Check in guests and watch attendance build." points={['Live scan count at the door', 'Guest names and status in one view', 'Capacity awareness while the event runs', 'Useful attendance numbers after the night ends']} image="analytics" secondaryImage="guests" /></section>

    <section className="organizer-reference-beyond"><div className="organizer-reference-shell"><Reveal><p className="organizer-reference-kicker"><ZapIcon size={15} /> Make the link do more</p><h2>Keep your audience<br /><em>close to the next thing.</em></h2><p className="organizer-reference-lede">A good event should not disappear when the lights go down. Give guests an easy way back to what you are building.</p></Reveal><div className="organizer-reference-beyond-grid"><Reveal><QrCodeIcon size={26} /><h3>Entry that respects the queue</h3><p>Give your door team a clean scan view. SCAN / VERIFY / WELCOME.</p><strong>SCAN / VERIFY / WELCOME</strong><small>Give your door team a clean scan view.</small><ul><li><CheckIcon size={14} />Fast checks for a busy entrance</li><li><CheckIcon size={14} />The guest list stays close to the team</li></ul></Reveal><Reveal><LinkIcon size={26} /><h3>A home for the programme</h3><p>Put your events behind one memorable organizer identity and let people see what is happening next.</p><strong>tiketi.events/your-name</strong><small>One place for the people who follow your work.</small><ul><li><CheckIcon size={14} />Keep upcoming events easy to find</li><li><CheckIcon size={14} />Your audience knows where to return</li></ul></Reveal><Reveal><TicketIcon size={26} /><h3>Ticket choices that make sense</h3><p>Shape a simple path from interest to checkout with REGULAR / VIP / VVIP options.</p><strong>REGULAR / VIP / VVIP</strong><small>Simple choices, clear prices, fewer questions.</small><ul><li><CheckIcon size={14} />Prices shown in BIF</li><li><CheckIcon size={14} />Built for local event rhythms</li></ul></Reveal></div></div></section>

    <section className="organizer-reference-reviews organizer-reference-shell"><Reveal><p className="organizer-reference-kicker"><UsersIcon size={15} /> The Tiketi point of view</p><h2>Build the kind of event<br /><em>you would attend.</em></h2><p className="organizer-reference-lede">Clear information, a smoother arrival, and fewer loose ends make space for the part people actually remember.</p></Reveal><div className="organizer-reference-review-grid">{[['One clear listing', '01 · DETAILS', 'Give guests the venue, time, ticket choice, and context they need before they say yes.'], ['A calmer door', '02 · CHECK-IN', 'Keep the guest list close to the team welcoming people into the room.'], ['A better read', '03 · INSIGHTS', 'Leave the event with useful signals about what sold, who arrived, and what to build next.'], ['A growing audience', '04 · FOLLOW', 'Make it easy for people who enjoyed this event to discover the next one.']].map(([title, user, copy], index) => <Reveal className={`organizer-reference-review review-${index}`} key={user}><b>{title}</b><small>{user}</small><blockquote>{copy}</blockquote><span>● ● ●</span></Reveal>)}</div></section>

    <section id="pricing" className="organizer-reference-pricing"><div className="organizer-reference-shell"><Reveal><p className="organizer-reference-kicker"><TicketIcon size={15} /> Pricing</p><h2>Simple pricing.<br /><em>Every feature.</em></h2><p className="organizer-reference-lede">Keep pricing straightforward and make the core organizer tools accessible. Final commission rates, settlement rules, and payment costs should be published only after they are confirmed.</p></Reveal><div className="organizer-reference-price-grid"><Reveal><article><span>Starter</span><small>ALWAYS FREE</small><p>Community and free-entry events</p><b>0% <i>commission, subject to final pricing policy</i></b></article></Reveal><Reveal><article className="is-popular"><span>General</span><small>MOST POPULAR</small><p>Conferences, concerts, and ticketed experiences</p><b>Commission: <i>confirm final rate before launch</i></b></article></Reveal><Reveal><article><span>Consumable</span><small>VENUE CREDIT</small><p>Tickets redeemed for food or drinks at the venue</p><b>Commission: <i>confirm final rate before launch</i></b></article></Reveal></div><Reveal className="organizer-reference-includes"><div><h3>Every plan includes</h3><p>Ticket scanning, shareable event link, sales and settlement tracking, team roles, analytics, and attendee management.</p></div><button onClick={() => navigate('auth-organizer')}>Get started <ArrowRightIcon size={15} /></button><ul>{['Ticket scanning', 'Shareable event link', 'Sales and settlement tracking', 'Team roles and access control', 'Sales analytics', 'Attendee and check-in management', 'Supported local payment methods'].map(item => <li key={item}><CheckIcon size={14} />{item}</li>)}</ul></Reveal></div></section>

    <section className="organizer-reference-faq organizer-reference-shell"><div><p className="organizer-reference-kicker"><ClipboardIcon size={15} /> FAQ</p><h2>Your guide to<br /><em>running events.</em></h2></div><div>{faqs.map(([question, answer], index) => <Reveal key={question} className="organizer-reference-faq-item"><button onClick={() => setOpenFaq(openFaq === index ? null : index)}><span><small>Q{index + 1}</small>{question}</span><ChevronDownIcon size={17} /></button>{openFaq === index && <p>{answer}</p>}</Reveal>)}</div></section>

    <section className="organizer-reference-final"><div className="organizer-reference-shell"><Reveal><p className="organizer-reference-kicker"><ZapIcon size={15} /> Your next event</p><h2>Start with the idea.<br /><em>We&apos;ll help with the rest.</em></h2><p>Open Tiketi, publish your event, share it with your audience, and start building the next experience.</p><button onClick={() => navigate('auth-organizer')}>Get started <ArrowRightIcon size={16} /></button><small>Free to get started · Built for Burundi&apos;s event organizers</small></Reveal></div></section>
  </main>
}
